services:
  loans-api:
    build: .
    container_name: loans-api
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/loansdb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: loans
      SPRING_DATASOURCE_PASSWORD: loans123
    depends_on:
      - mysql
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: loans-mysql
    environment:
      MYSQL_DATABASE: loansdb
      MYSQL_USER: loans
      MYSQL_PASSWORD: loans123
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin:5.2
    container_name: loans-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: rootpass
    ports:
      - "8081:80"
    depends_on:
      - mysql
    restart: unless-stopped

volumes:
  dbdata:
